--INSERT INTO products (id, title, descri, price, img, category)
--VALUES (5, "Kemp Stone Studded Temple Temple Choker Necklace Set", "Brass Based Temple Choker Necklace in Golden,Allured with Kemp Stones and Artificial Pearls,It is Enclosed with an Adjustable Cord.", 2880, "https://medias.utsavfashion.com/media/catalog/product/cache/1/image/500x/040ec09b1e35df139433887a97daa66f/k/e/kemp-stone-studded-temple-temple-choker-necklace-set-v1-jkc7116.jpg","jewellery"),
--(6, "Stone Studded Openable Bangle Pair", "Alloy Based Openable Bangle Pair in Golden and Allured with Stones", 1500, "https://medias.utsavfashion.com/media/catalog/product/cache/1/image/500x/040ec09b1e35df139433887a97daa66f/s/t/stone-studded-openable-bangle-pair-v1-jkw1129.jpg","jewellery"),
--(7, "Kundan Jhumka Style Earrings", "Alloy Based Jhumka Style Earrings in Golden and Pink and Allured with Kundan, Beads and Artificial Pearls and Its Length and Width is 6 and 3 cm respectively ", 1200, "https://medias.utsavfashion.com/media/catalog/product/cache/1/image/500x/040ec09b1e35df139433887a97daa66f/k/u/kundan-jhumka-style-earrings-v1-jpm7146.jpg","jewellery"),
--(8, "Stone Studded Choker Necklace Set", "Alloy Based Choker Necklace in Golden and Off White and Adorned with Stones, Kundan and Beads and Available with a Matching Pair of Earrings and a Maang Tikka",1700, "https://medias.utsavfashion.com/media/catalog/product/cache/1/image/500x/040ec09b1e35df139433887a97daa66f/s/t/stone-studded-choker-necklace-set-v1-jcv183_1.jpg","jewellery"),
--(9, "LG Tv", "The Classic St. Mawes, an integral part of the flagship Classic Collection, is a slim timepiece that sits perfectly on your wrist.", 30000, "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl87GS2EDux74KsyYdINISidpwSiOO5vxi5g&usqp=CAU","Electronic gadgets"),
--(10, "HP Laptop", "This G-Star Men's Denim Ebro Baseball Trucker Cap is created out of two different fabrics.", 65000, "https://lh3.googleusercontent.com/spp/AOgFAqOynK6jOOf6hrQgVJjYoknwuEVO1q0bpJ7jaJsCaZUscIW8MGyRRyXet0OZBBjQOF1jUBQ0oCjOcxA2e38O79tWg3IKM0SMVmftLnvL9cfExmX1YvOfB8PIJnfvr2F42TT9ONzS3Erdo4vreKth1psPC46Sz-OjP0treOzs3ZY9saNaBh_aF6HH8l8ydoN9fSKtg8oWBbc=s512-rw-pd-pc0x00ffffff","Electronic gadgets"),
--(11, "Iphone 15", "SmartphoneDual,SIM4GWireless, ChargingiOSWith, OLED, DisplayBlackWater, ResistantNanoEPEAT-registered. ", 80000, "https://lh3.googleusercontent.com/spp/AOgFAqOxnNSIzlZXZ1sORoABNE_XbjOKIhFD_ZA9p06V3TQdHj26g870GwHp1Tq_nf_NF5ZshX7I5i6klE3F3MLKGMGZiJScFs26yX12ViVx2P1n4iTTmejE6pv6XPbXkjf4dml4yy6D3OnWzXLByXwEknlxOL7BXtu1cDS9hEQyU5oY4H27EFlbCFC0EusLsmYkVmsEf0wH9cE=s512-rw-pd-pc0x00ffffff","Electronic gadgets"),
--(12, "Apple Arpods max", "Noise Cancelling With Microphone With Touch ControlsSiri With Adaptive EQ, Truewireless , True Wireless, TWS, earbuds, ear buds Bluetooth earphone, headphones, headphone",15000, "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/airpods-max-select-skyblue-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604022365000","Electronic gadgets"),
--(13, "Zip Through Hoodie", "Our zip through hoodie Made from a blend of cotton that's super soft, it's brushed inside to ensure maximum comfort. The zip-through feature allows for easy layering, and the added hood makes it essential for cooler days.", 800, "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/SearchAlt/224x336/166334.jpg","clothing"),
--(14, "Sleeveless Crew Neck Tiered Summer Maxi Dress", "This product has a looser fit than usual. Warmer days are calling and our tiered maxi dress is the ideal companion for sunshine strolls, ice-cream eating and sipping ice-cold drinks at the beach bar",900, "https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G29/shotview-315x472/568/151-081s.jpg","clothing"),
--(15, "Cream Embroidered Mesh Party Dress (3mths-7yrs)", "Perfect for weddings, this wonderful dress has embroidered and mesh detailing for a magical look, finished with all-over designs and a round collar, with a button-up fastening to the back.", 500, "https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G54/shotview-315x472/4201/192-442s.jpg","clothing"),    
--(16, "Navy Blue/Tan Brown Colourblock Hoodie and Jogger Set (3mths-7yrs)", "Better Cotton - By choosing our cotton products, you’re supporting our investment in Better Cotton's mission. Better Cotton is sourced via a chain of custody model called mass balance",600, "https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G85/shotview-315x472/4713/D39-334s.jpg","clothing");  
 select * from products;

--CREATE TABLE products (id INTEGER,title VARCHAR(200),descri VARCHAR(1000),price INTEGER,img VARCHAR(1000),category VARCHAR(200));

--PRAGMA TABLE_INFO(products);

--INSERT INTO products (id, title, descri, price, img, category)
--VALUES (17, "The Brown Metro Movers Backpack", "Full Grain Leather Backpack Men Travel Backpack Cool Backpacks, Unihandmade", 4786, "https://imagetolink.com/ib/VvlrHlfwsB.png","backpacks"),
--(18, "The Metro Movers Black Backpack", "Travel backpack carry on travel backpack essentials traveling backpacks carry on travel backpacks carry on travel backpack essential travel backpack for woman travel aesthetic travel", 4500, "https://imagetolink.com/ib/xDOcHtjfDD.png","backpacks"),
--(19, "The Grey Metro Movers Backpack", "Full Grain Leather, Cotton Lining, Brass Hardware-Inside one zipper pocket, one laptop sleeve", 3600, "https://imagetolink.com/ib/9YdWDm4uWx.png","backpacks"),
--(20, "The Metro Movers Black Backpack", "Full Grain Leather Backpack Men Travel Backpack Cool Backpacks – Unihandmade ",4700, "https://imagetolink.com/ib/sBuwCLDr3T.png","backpacks"),
--(21, "Retro Solid Green Backpack", "Travel backpack carry on travel backpack essentials traveling backpacks carry on travel backpacks carry on travel backpack essential travel backpack for woman travel aesthetic travel", 4640, "https://www.bygoods.com/media/catalog/product/cache/1/image/800x/1dd3c1054c06760f44f47a9755af505d/t/b/tb2ex1devxxxxxtxpxxxxxxxxxx-775817107_1.jpg","backpacks"),
--(22, "The Red Metro Movers Backpack", "Full Grain Leather, Cotton Lining, Brass Hardware-Inside one zipper pocket, one laptop sleeve", 4500, "https://tse3.mm.bing.net/th/id/OIP.A1nkIyKNk9vlnOLMpSf5aAHaHa?pid=ImgDet&w=207&h=207&c=7","backpacks"),
--(23, "The Metro Movers Black Backpack", "Travel backpack carry on travel backpack essentials traveling backpacks carry on travel backpacks carry on travel backpack essential travel backpack for woman travel aesthetic travel", 3900, "https://i.pinimg.com/736x/03/c7/b0/03c7b09347143ab8a919602e190e4983.jpg","backpacks"),
--(24, "Retro Solid Brown Backpack", "Full Grain Leather Backpack Men Travel Backpack Cool Backpacks – Unihandmade",4500, "https://cdn.shopify.com/s/files/1/1126/9768/products/1_6416795a-5809-4928-9736-bf195fa0ab86_grande.jpg?v=1551476040","backpacks");
